name: Cypress Tests for Jupiter Shopping

on: 
  workflow_dispatch:
  push:

jobs:
  install-ubuntu-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          runTests: false

  test-ubuntu-chrome:
    runs-on: ubuntu-latest
    needs: install-ubuntu-chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome


  install-and-test-windows-edge:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: edge
